### ISSUE TITLE
send Shlomi assets due to his notes.

### ISSUE THREAD

**Issue by moriahb** [shenkarlab/2035#21]

**Comment by shlomimihaeli** [comment]
in general, i need slices of everything that is not html, inclusing png headlines.
1. first headline png
2. video placements 
3. more button (only three dots) PNG
4. two lines bottom border, one pixel vertically.
5. back pixel (grid) exactly like in PSD

**Comment by shlomimihaeli** [comment]
you can put it all in "slices" folder

**Comment by moriahb** [comment]
all in. +
